"""fix account type enum

Revision ID: 662d1e1c652f
Revises: e407e3fe3337
Create Date: 2025-05-29 19:25:20.707575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662d1e1c652f'
down_revision = 'e407e3fe3337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('account_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('account_ibfk_1'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
